# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nodemass Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  env:
    PROD_ARTIFACT_NAME: nodemass
    PROD_ARTIFACT_FILE_NAME: modemass-${{ github.run_id }}.tgz
    BUILD_OUTPUT: ./dist

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependancies
        run: npm i

      - name: Create Build
        run: npm run build

      - name: Archive Artifacts
        run: tar -czvf ${{ env.PROD_ARTIFACT_FILE_NAME }} -C ${{ env.BUILD_OUTPUT }} .

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROD_ARTIFACT_NAME }}
          path: ./${{ env.PROD_ARTIFACT_FILE_NAME }}
